allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@astrojs/starlight@0.40.0'
  - '@expressive-code/core@0.43.1'
  - '@expressive-code/plugin-frames@0.43.1'
  - '@expressive-code/plugin-shiki@0.43.1'
  - '@expressive-code/plugin-text-markers@0.43.1'
  - astro-expressive-code@0.43.1
  - astro@6.4.5
  - expressive-code@0.43.1
  - rehype-expressive-code@0.43.1
